// src/utils/pdfGenerator.js

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const currencyFormatter = new Intl.NumberFormat("en-IN", {
  style: "currency",
  currency: "INR",
});

/**
 * Generates and downloads a professional A4 PDF invoice.
 *
 * @param {Object} invoice - Invoice data object.
 * @param {string} invoice.invoiceNumber - Unique invoice number.
 * @param {string} invoice.customerName - Name of the customer.
 * @param {string} invoice.productName - Name of the product sold.
 * @param {number} invoice.quantity - Quantity sold.
 * @param {number} invoice.sellingPrice - Price per unit.
 * @param {number} invoice.totalAmount - Total invoice amount.
 * @param {string} invoice.invoiceDate - Invoice date (ISO string or date-like value).
 */
export const generateInvoicePDF = (invoice) => {
  // -------------------------------
  // Initialize A4 Document
  // -------------------------------
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginX = 14;

  // -------------------------------
  // Header - Company Title & Subtitle
  // -------------------------------
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(33, 37, 41);
  doc.text("Inventory Management System", pageWidth / 2, 20, {
    align: "center",
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.setTextColor(108, 117, 125);
  doc.text("Sales Invoice", pageWidth / 2, 28, { align: "center" });

  // Divider line under header
  doc.setDrawColor(222, 226, 230);
  doc.setLineWidth(0.5);
  doc.line(marginX, 33, pageWidth - marginX, 33);

  // -------------------------------
  // Invoice Meta Details
  // -------------------------------
  const formattedDate = invoice.invoiceDate
    ? new Date(invoice.invoiceDate).toLocaleDateString()
    : "";

  doc.setFontSize(11);
  doc.setTextColor(33, 37, 41);

  const metaStartY = 42;
  const lineGap = 7;

  doc.setFont("helvetica", "bold");
  doc.text("Invoice Number:", marginX, metaStartY);
  doc.setFont("helvetica", "normal");
  doc.text(String(invoice.invoiceNumber ?? ""), marginX + 40, metaStartY);

  doc.setFont("helvetica", "bold");
  doc.text("Invoice Date:", marginX, metaStartY + lineGap);
  doc.setFont("helvetica", "normal");
  doc.text(formattedDate, marginX + 40, metaStartY + lineGap);

  doc.setFont("helvetica", "bold");
  doc.text("Customer Name:", marginX, metaStartY + lineGap * 2);
  doc.setFont("helvetica", "normal");
  doc.text(
    String(invoice.customerName ?? ""),
    marginX + 40,
    metaStartY + lineGap * 2
  );

  // -------------------------------
  // Table - Invoice Line Item
  // -------------------------------
  const tableStartY = metaStartY + lineGap * 2 + 10;

  autoTable(doc, {
    startY: tableStartY,
    head: [["Product Name", "Quantity", "Selling Price", "Total Amount"]],
    body: [
      [
        invoice.productName ?? "",
        String(invoice.quantity ?? ""),
        currencyFormatter.format(invoice.sellingPrice ?? 0),
        currencyFormatter.format(invoice.totalAmount ?? 0),
      ],
    ],
    theme: "grid",
    headStyles: {
      fillColor: [13, 110, 253],
      textColor: 255,
      fontStyle: "bold",
      halign: "center",
    },
    bodyStyles: {
      halign: "center",
      textColor: [33, 37, 41],
    },
    styles: {
      lineColor: [222, 226, 230],
      lineWidth: 0.2,
      cellPadding: 4,
      fontSize: 10,
    },
    margin: { left: marginX, right: marginX },
  });

  // -------------------------------
  // Total Amount Summary
  // -------------------------------
  const afterTableY = doc.lastAutoTable.finalY + 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(
    `Total Amount: ${currencyFormatter.format(invoice.totalAmount ?? 0)}`,
    pageWidth - marginX,
    afterTableY,
    { align: "right" }
  );

  // -------------------------------
  // Footer
  // -------------------------------
  const footerY = pageHeight - 25;

  doc.setDrawColor(222, 226, 230);
  doc.line(marginX, footerY, pageWidth - marginX, footerY);

  doc.setFont("helvetica", "italic");
  doc.setFontSize(10);
  doc.setTextColor(108, 117, 125);
  doc.text("Thank you for your business!", pageWidth / 2, footerY + 7, {
    align: "center",
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(
    "Generated by Inventory Management System",
    pageWidth / 2,
    footerY + 13,
    { align: "center" }
  );

  // -------------------------------
  // Save PDF
  // -------------------------------
  doc.save(`Invoice_${invoice.invoiceNumber}.pdf`);
};